parameters:
  - name: branch
    env: GIT_BRANCH
    rule: ""
    required: true
  - name: AWS_STORAGE_BUCKET_NAME
    env: AWS_STORAGE_BUCKET_NAME
    rule: ""
    required: true
  - name: AWS_WEB_ASSETS_BUCKET_NAME
    env: AWS_WEB_ASSETS_BUCKET_NAME
    rule: ""
    required: true
  - name: DB_NAME
    env: DB_NAME
    rule: ""
    required: true
  - name: SYNC_DOMAIN
    env: SYNC_DOMAIN
    rule: ""
    required: true
  - name: WEB_DOMAIN
    env: WEB_DOMAIN
    rule: ""
    required: true
  - name: SALESFORCE_REDIRECT_URI
    env: SALESFORCE_REDIRECT_URI
    rule: ""
    required: true
  - name: AWS_APP_BUCKET_NAME
    env: AWS_APP_BUCKET_NAME
    rule: ""
    required: true
htmldir: "{{ must_env `HTMLDIR` }}"
#auth:
#  amzn_oidc:
#    claim: email
#    matchers:
#      - suffix: "@gmail.com"
