FROM python:3.9.6-slim
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE=1
RUN apt-get update \
    && apt-get install -y build-essential python3-dev default-libmysqlclient-dev \
    && apt-get install -y ffmpeg libavcodec-extra \
    && apt-get install -y jq awscli \
    && apt-get clean
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

RUN chmod +x entrypoint.sh
ENTRYPOINT ["/code/entrypoint.sh"]
CMD ["gunicorn", "-b", "0:80", "config.wsgi:application", "--workers", "2", "--threads", "6", "--timeout","300", "--keep-alive", "30"]