name: Deploy container image to AWS Lambda
on:
  push:
    branches:
     - main
env:
  AWS_ACCOUNT_ID: 267751904634
  AWS_ROLE_NAME: nasu-prod-github-actions-role
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read
jobs:
  aws-deploy:
    name: nasu-prod-stata-update-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          LAMBDA_FUNCTION_NAME: nasu-prod-updata-state
          ECR_REPOSITORY: nasu/prod/updata-state
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          
        working-directory: ./aws/lambda_function/update_states
        
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to Lambda.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          #  Update Lambda configuration
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  test:
    name: nasu-prod-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          LAMBDA_FUNCTION_NAME: nasu-prod-updata-state
          ECR_REPOSITORY: nasu/prod/updata-state
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          
        working-directory: ./aws/lambda_function/update_states
        
        run: |
          sleep 10
          echo hello